### PR TITLE
fix(homeDirection): use nav_bearing instead of osd_heading

### PR DESCRIPTION
**Pull request by TobiasBales**
this should fix the issue with inconsistent home direction

### CODE REVIEW

**Comment by StewLG** [comment]
Happy to test; can you provide a binary? This bug is the #1 thing holding PlayUAV back.

**Comment by TobiasBales** [comment]
The first attempt (using nav_bearing) did not work out since nav_bearing is only set in modes != manual. We are trying another vector now.
Sebastian wanted to give it a try today, but you can try it too.
The latest binary for this pr is available https://circleci.com/api/v1/project/TobiasBales/PlayuavOSD/latest/artifacts/0/$CIRCLE_ARTIFACTS/PlayuavOSD.hex?branch=fix-heading&filter=successful
Keep in mind no guarantees at all about it ;)

And I do agree, it is the number one thing on the list and we are eager to get it done.

**Comment by trgFPV** [comment]
Using the minimosd code did not help, it seems like the home arrow is now about 180°-170° Degrees off. Tobi or I will make a testing firmware which will display the current osd_home_bearing, osd_heading and bearing of the home arrow.

**Comment by StewLG** [comment]
I've compiled up a version with the debug statements (these: https://github.com/TobiasBales/PlayuavOSD/pull/20/commits/9097399db94d95d0dc6d68cdabecd5e8dc640024). The arrow and computed angles seemed to work adequately in backyard testing, but the distances involved were only 10-15 meters. I also tested with a hard coded set of five coordinates and tested rotating the flight controller for many combinations of those five lat/lon pairs, varying home and current position. That was tedious, but also seemed to work properly.

I intend to fly with the debug statements and (as per usual) DVR everything.

**Comment by trgFPV** [comment]
StewLg, do you have flown with the debug firmware yet? I have done around 10 Flights with the debug firmware and the home arrow works fine for me. Looking forward to your feed back :)

**Comment by TobiasBales** [comment]
fix(homeDirection): use minimosd-extra style code

apparently the approximations used by Fast_Cos etc caused an issue at times

**Comment by StewLG** [comment]
I flew yesterday and it wasn't working for me:

https://vimeo.com/182626597

BUT, keep in mind, I have only flown what was (prior to the merge of commit 555bfe above) master + the debug statements. I did not take commit 87d9aac. At the time the comments indicated you thought this branch was a dead-end; now I'm not sure at all what is going on here with all the various attempts at a fix and this branch.

I can fly master again - or something else - again. Just let me know exactly what to test. I intend to fly in a matter of hours, so a quick response should get you another test in short order.

**Comment by TobiasBales** [comment]
@StewLG yes, please do test the current master build and report back then

**Comment by StewLG** [comment]
No joy. Here's footage from flying master today:

https://vimeo.com/182806612/f93d3b0bec

If it isn't obvious, bring up the home location on Google Earth and follow along as I fly the circuit. You'll see the arrow is more wrong than right.

I regret not re-enabling the debugging information you disabled with this commit https://github.com/TobiasBales/PlayuavOSD/commit/2256a8c84556eae1de1ea1c3343b2d507dc73052. I suggest you re-enable this debugging information so that all flyers will have it to submit for troubleshooting. 

Suggestions welcome. I'm depressed - this plane is currently crippled by this problem. I am really confused how anyone else could have this code work at all, let alone trgFPV's 10 times.

**Comment by TobiasBales** [comment]
I will re-add a build with debug information.
One question - is your compass calibrated? On planes I think it isn't mandatory

**Comment by StewLG** [comment]
Compass is calibrated. It is reading correctly - at least within 5-10 degrees, which isn't enough difference to explain the inaccuracies I'm seeing, which can be as much as 180 degrees.  When I had debug information enabled before (https://vimeo.com/182626597) I could see the rotary compass UI was showing the proper compass direction (NW when headed NW, etc.), and it agreed with the debug variable (osd_heading). So it does seem to me my plane is giving good input to the bearing algorithm.

Any other ideas?

**Comment by TobiasBales** [comment]
Maybe you can compare notes with @trgFPV because I haven't flow properly in close to a year now and just put some of my spare time into the project (but it makes checking things out rather hard)

**Comment by trgFPV** [comment]
I'm sorry the home arrow still does not work for you, at the same time I'm amazed how it could work perfectly fine for me while it does not for you?!
Still it is evident there is something wrong with the code that determines the absolute heading between the aircraft and the takeoff point. I will have another look when I have time.

**Comment by StewLG** [comment]
trgFPV, can you share footage of it working for you? Have you reviewed my footage?

I am also amazed it could malfunction for me, and work for you.

**Comment by trgFPV** [comment]
Not right now, I have to setup my new dvr first. I will share footage once that is sorted

**Pull request merged**
